Pigeon.MVC/Controllers/CompeticaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pigeon.Dal.Repository;
using Pigeon.Model;

namespace Pigeon.MVC.Controllers
{
    public class CompeticaoController : Controller
    {
        // GET: Competicao
        public ActionResult Index()
        {
            return View(new CompeticaoRepository().GetAllCompeticao());
        }

        [HttpGet]
        [Route("Competicao/{id}")]
        public ActionResult Competicao(int id)
        {
            Competicao minhaCompeticao = new CompeticaoRepository().GetCompeticaoById(id);
            List<Prova> meuItens = new ProvaRepository().GetProvaByCompeticaoId(id);
            ViewBag.meusItems = meuItens;

            ViewBag.minhaCompeticao = minhaCompeticao;


            return View("Detail");
        }
        //Adicionar item
        [HttpPost]
        [Route("Competicao/addprova")]
        public ActionResult adcionarItem(int idCompeticao, Prova itemGravar)
        {
            try
            {

                itemGravar.competicaoId = idCompeticao;
                new ProvaRepository().NovaProva(itemGravar);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(1);
        }

        [HttpPost]
        [Route("Competicao/CadastrarCompeticao")]
        public ActionResult CadastrarCompeticao(Competicao minhaCompeticao)
        {
            try
            {
                new CompeticaoRepository().NovaCompeticao(minhaCompeticao);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(minhaCompeticao.id);
        }

        [HttpPost]
        [Route("Competicao/ExcluirCompeticao")]
        public ActionResult ExcluirCompeticao(int id)
        {
            try
            {
                new CompeticaoRepository().ExcluirCompeticao(id);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(id);
        }

        //Adicionar item
        [HttpPost]
        [Route("competicao/excluirProva")]
        public ActionResult excluirProva(int id)
        {
            try
            {
                new ProvaRepository().ExcluirProva(id);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(1);
        }

    }
}

Pigeon.MVC/Views/Competicao/Detail.cshtml
@using Pigeon.Model
@model Prova

<link rel="stylesheet" href="~/Content/css/Switch.css">
<link rel="stylesheet" href="~/Content/css/Pombo.css">

<div class="col-md-10 offset-1 margem-top-25">
    <h3>Descrição da competição: @ViewBag.minhaCompeticao.nome</h3>
    <h2>Data:</h2>
    <p>@ViewBag.minhaCompeticao.ano.Date</p>
    </br>
    <button onclick="openNewProvaModal();" class="btn btn-primary">Adicionar nova prova</button>

    <h2>Provas da competicao:</h2>
    @if (ViewBag.meusItems != null)
    {
        <table style="width:100%">
            <tr>
                <th>Tipo</th>
                <th>Descricao</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Deletar</th>
            </tr>

            @foreach (var item in ViewBag.meusItems)
            {
            <tr>
                <td>@item.tipo</td>
                <td>@item.descricao</td>
                <td>@item.latitude</td>
                <td>@item.longitude</td>
                <td><img class="responsivo" src="~/Content/imgs/icons/remove.png" height="25" onclick="ModalExclusaoItem(@item.id);" /></td>

            </tr>
            }
        </table>
        <br />
    }

    else
    {
        <p>A compra não possui itens.</p>
    }

</div>


<script>

    $(document).ready(
        function () {
            MudarSelecaoPagina("Competicoes");
        }
    );

//Item da compra

function openNewProvaModal() {
    var html =
        `<div class="row">

        <div class="form-group col-md-6">
            <label for="data">Tipo:</label>
            <!--<input type="text" class="form-control" id="Tipo" placeholder="Meio-fundo">-->
            <select id="ddlTipo" class="form-control">
            <option selected> Fundo </option>
            <option> Meio-fundo </option>
            </select>
            <div class="invalid-feedback">
                Digite um tipo válido.
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="data">Descricao:</label>
            <input type="text" class="form-control" id="Descricao" placeholder="Prova em engenheiro navarro - clube betinense">
            <div class="invalid-feedback">
                Digite uma descrição válida.
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="data">latitude:</label>
            <input type="text" class="form-control" id="latitude" placeholder="-11.33">
            <div class="invalid-feedback">
                Digite um valor válido(Ex: 11.22).
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="data">longitude:</label>
            <input type="text" class="form-control" id="longitude" placeholder="22.111">
            <div class="invalid-feedback">
                Digite um valor válido(Ex: 11.22).
            </div>
        </div>


    </div>`;

    ModalShow("Cadastrar Prova", "CadastrarProvaPre();", "", "Cadastrar", "Cancelar", html);
}

function ModalExclusaoItem(icon) {
        var html = "Tem certeza que deseja excluir o cadastro do Compra '" + icon + "'?";
    ModalShow("Exclusão de Item", "ExcluirItemPre(" +icon+");", "", "Sim", "Não", html);
}

    function CadastrarProvaPre() {
        if (!ValidacaoProva()) return;

        var url = "@Url.Action("adcionarItem", "Competicao")";
        var params = {
        idCompeticao: @ViewBag.minhaCompeticao.id,
        itemGravar: {
                id: 0,
                latitude: $("#latitude").val(),
                longitude: $("#longitude").val(),
                descricao: $("#Descricao").val(),
                tipo: $("#ddlTipo option:selected").text(),
                competicaoId: 0,
            },
        };
    $("#Modal").modal("hide");
    ProgressBar();
        $.post(url, params, CadastrarProvaPos);
}

function ValidacaoProva() {
    var valido = true;
    //var campo = $("#ddlTipo option:selected");
    //if (campo.val() == "" || typeof campo.val() != "string") {
    //    InvalidarPreenchimento(campo, "Nome Inválido.");
    //    valido = false;
    //}
    campo = $("#Descricao");
    if (campo.val() == "" || typeof campo.val() != "string") {
        InvalidarPreenchimento(campo, "Valor Inválido.");
        valido = false;
    }
    campo = $("#latitude");
    if (campo.val() == "" || isNaN(parseFloat(campo.val())) ) {
        InvalidarPreenchimento(campo, "Valor Inválido.");
        valido = false;
    }
    campo = $("#longitude" || isNaN(parseFloat(campo.val())));
    if (campo.val() == "") {
        InvalidarPreenchimento(campo, "Valor Inválido.");
        valido = false;
    }

    return valido;
}

function CadastrarProvaPos(id) {
    StopProgressBar();
    if (!$.isNumeric(id)) {
        Mensagem("erro", "Ocorreu um erro inesperado. Cadastro não efetuado!")
    }
    else {
        Mensagem("sucesso", "Cadastrado com Sucesso!")
    }
}

function ExcluirItemPre(id) {

    var url = "@Url.Action("excluirProva", "Competicao")";
    var params = {
        id: id,
    };
    $("#Modal").modal("hide");
    ProgressBar();
    $.post(url, params, ExcluirItemPos);
}

function ExcluirItemPos(id) {
            StopProgressBar();
            if (!$.isNumeric(id)) {
                Mensagem("erro", "Ocorreu um erro inesperado. Exclusão não efetuada!")
            }
            else {
                $("#Pombo-" + id).remove();
                Mensagem("sucesso", "Excluído com Sucesso!")
         }
}

</script>

Pigeon.MVC/Views/Competicao/Index.cshtml
@model IEnumerable<Pigeon.Model.Competicao>


@using Pigeon.Model


<link href="~/Content/css/Pombo.css" rel="stylesheet">


<div class="row margem-top-25">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"> <img src="~/Content/imgs/icons/search.png" height="25" /> </div>
            </div>
            <input type="text" class="form-control" id="tbxBuscar" placeholder="Buscar">
        </div>
    </div>
    <div class="col-md-1">
        <img class="clicavel" src="~/Content/imgs/icons/add_circle.png" height="36" onclick="ModalCadastroCompeticao();" />
    </div>

</div>

<div class="row margem-top-10">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <table class="table">
            <thead>
                <tr class="text-center">
                    @*<th scope="col">ID</th>*@
                    <th scope="col">Ano</th>
                    <th scope="col">Nome</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Competicao P in Model)
                {
                    <tr id="Pombo-@P.id" class="text-center selecionar" >
                        <td onclick="RedirectToCompeticao(@P.id)">@P.id</td>
                        <td onclick="RedirectToCompeticao(@P.id)">@P.ano</td>
                        <td onclick="RedirectToCompeticao(@P.id)">@P.nome</td>
                        <td><img class="responsivo" src="~/Content/imgs/icons/remove.png" height="25" onclick="ModalExclusaoCompeticao(this);" /></td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<script src="~/Scripts/Competicao.js"></script>

<script>

    $(document).ready(
        function () {
            MudarSelecaoPagina("Competicoes");
        }
    );
    function RedirectToCompeticao(id)
    {
        window.location.href = "/Competicao/" + id;
    }

    function CadastrarCompeticaoPre() {
        if (!ValidacaoCompeticao()) return;

        var url = "@Url.Action("CadastrarCompeticao", "Competicao")";
            var params = {
                id: 0,
                ano: $("#data").val(),
                nome: $("#nome").val(),
         };
            $("#Modal").modal("hide");

           $.post(url, params, CadastrarCompeticaoPos);
    }

    function ExcluirCompeticaoPre(id)
    {

        var url = "@Url.Action("ExcluirCompeticao", "Competicao")";
            var params = {
                Id: id,
         };
            $("#Modal").modal("hide");
        $.post(url, params, ExcluirCompeticaoPos);
    }
</script>