Pigeon.MVC/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pigeon.Dal.Repository;
using Pigeon.Model;

namespace Pigeon.MVC.Controllers
{
    public class CompraController : Controller
    {

        // GET: Compra
        public ActionResult Index()
        {
            return View(new CompraRepository().GetAllCompras().ToList());
        }
        [HttpGet]
        [Route("compra/{id}")]
        public ActionResult Compras(int id)
        {
            Compra minhaCompra = new CompraRepository().GetCompraById(id);
            List<Item> meuItens = new ItemRepository().GetItemByCompraId(id);
            ViewBag.meusItems = meuItens;
            Double total = 0;
            if (meuItens != null) {
                foreach (var item in meuItens)
                {
                    total += item.valor;
                }
            }

            ViewBag.minhaCompra = minhaCompra;

            ViewBag.subtotal = total;
            return View("Detail");
        }
        //Adicionar item
        [HttpPost]
        [Route("compra/{idCompra}/additem")]
        public ActionResult adcionarItem(int idCompra, Item itemGravar)
        {
            try
            {
                itemGravar.compraID = idCompra;
                new CompraRepository().NovoItem(itemGravar);
            }
            catch (Exception ex) {
                return Json(ex.Message);
            }
            return Json(1);
        }
        //Adicionar item
        [HttpPost]
        [Route("compra/{idItem}/excluirItem")]
        public ActionResult excluirItem(int id)
        {
            try
            {
                new ItemRepository().ExcluirItem(id);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(1);
        }

        [HttpPost]
        [Route("Compra/CadastrarCompra")]
        public ActionResult CadastrarCompra(Compra compra)
        {
            try
            {
                new CompraRepository().NovaCompra(compra).ToString();
            }
            catch (Exception ex) {
                return Json(ex.Message);
            }
            return Json(compra.id);
        }

        [HttpPost]
        [Route("Compra/ExcluirCompra/{id}")]
        public ActionResult ExcluirCompra(int id)
        {
            try
            {
                new CompraRepository().ExcluirCompra(id);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(id);
        }
    }
}

Pigeon.MVC/Views/Compra/Detail.cshtml
@using Pigeon.Model
@model Compra

<link rel="stylesheet" href="~/Content/css/Switch.css">
<link rel="stylesheet" href="~/Content/css/Pombo.css">

<div class="col-md-10 offset-1">
    <h3>Descrição da compra: @ViewBag.minhaCompra.descricao</h3>
    <h2>Data:</h2>
    <p>@ViewBag.minhaCompra.data.Date</p>
    </br>
    <button onclick="openNewItemModal();" class="btn btn-primary">Adicionar novo item</button>

    <h2>Itens da compra:</h2>
    @if (ViewBag.meusItems != null)
    {
    <table style="width:100%">
        <tr>
            <th>Nome</th>
            <th>Valor</th>
            <th>Deletar</th>
        </tr>

        @foreach (var item in ViewBag.meusItems)
        {
        <tr>
            <td>@item.Nome</td>
            <td>@item.valor</td>
            <td><img class="responsivo" src="~/Content/imgs/icons/remove.png" height="25" onclick="ModalExclusaoItem(@item.id);" /></td>

        </tr>
        }
    </table>
            <br />
            <p>Total: @ViewBag.subtotal</p>
     }

     else{
            <p>A compra não possui itens.</p>
        }

    </div>


<script>


//Item da compra

function openNewItemModal() {
    var html =
        `<div class="row">

        <div class="form-group col-md-6">
            <label for="data">Nome:</label>
            <input type="text" class="form-control" id="Nome" placeholder="Briquê">
            <div class="invalid-feedback">
                Digite um nome válido.
            </div>
        </div>

        <div class="form-group col-md-6">
            <label for="data">Valor:</label>
            <input type="text" class="form-control" id="valor" placeholder="Briquê">
            <div class="invalid-feedback">
                Digite um valor numerico válido.
            </div>
        </div>
        

    </div>`;

    ModalShow("Cadastrar Compra", "CadastrarItemPre();", "", "Cadastrar", "Cancelar", html);
}

    function ModalExclusaoItem(icon) {
        var html = "Tem certeza que deseja excluir o cadastro do Compra '" + icon + "'?";
    ModalShow("Exclusão de Item", "ExcluirItemPre(" +icon+");", "", "Sim", "Não", html);
}

function CadastrarItemPre() {
    if (!ValidacaoItem()) return;

    var url = "/compra/" +@ViewBag.minhaCompra.id+"/additem";
    var params = {
        id: 0,
        Nome: $("#Nome").val(),
        valor: $("#valor").val(),
    };
    $("#Modal").modal("hide");
    ProgressBar();
    $.post(url, params, CadastrarItemPos);
}

function ValidacaoItem() {
    var valido = true;
    var campo = $("#Nome");
    if (campo.val() == "") {
        InvalidarPreenchimento(campo, "Nome Inválida.");
        valido = false;
    }
    campo = $("#valor");
    if (campo.val() == "") {
        InvalidarPreenchimento(campo, "Valor Inválida.");
        valido = false;
    }

    return valido;
}

function CadastrarItemPos(id) {
    StopProgressBar();
    if (!$.isNumeric(id)) {
        Mensagem("erro", "Ocorreu um erro inesperado. Cadastro não efetuado!")
    }
    else {
        Mensagem("sucesso", "Cadastrado com Sucesso!")
    }
}

function ExcluirItemPre(id) {

    var url = "/compra/"+id+"/excluirItem";
    var params = {
        id: id,
    };
    $("#Modal").modal("hide");
    ProgressBar();
    $.post(url, params, ExcluirItemPos);
}

function ExcluirItemPos(id) {
            StopProgressBar();
            if (!$.isNumeric(id)) {
                Mensagem("erro", "Ocorreu um erro inesperado. Exclusão não efetuada!")
            }
            else {
                $("#Pombo-" + id).remove();
                Mensagem("sucesso", "Excluído com Sucesso!")
         }
}

</script>

Pigeon.MVC/Views/Compra/Index.cshtml
@model IEnumerable<Pigeon.Model.Compra>


@using Pigeon.Model


<link href="~/Content/css/Pombo.css" rel="stylesheet">


<div class="row margem-top-25">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"> <img src="~/Content/imgs/icons/search.png" height="25" /> </div>
            </div>
            <input type="text" class="form-control" id="tbxBuscar" placeholder="Buscar">
        </div>
    </div>
    <div class="col-md-1">
        <img class="clicavel" src="~/Content/imgs/icons/add_circle.png" height="36" onclick="ModalCadastroCompra();" />
    </div>

</div>

<div class="row margem-top-10">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <table class="table">
            <thead>
                <tr class="text-center">
                    @*<th scope="col">ID</th>*@
                    <th scope="col">Descricão</th>
                    <th scope="col">Data realizada</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Compra P in Model)
                {
                    <tr id="Pombo-@P.id" class="text-center selecionar">
                        @*<td>@item.Id</td>*@
                        <td onclick="redirectToCompra(@P.id)">@P.descricao</td>
                        <td onclick="redirectToCompra(@P.id)">@P.data</td>
                        <td><img class="responsivo" src="~/Content/imgs/icons/remove.png" height="25" onclick="ModalExclusaoCompra(this);" /></td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>


<script src="~/Scripts/Compra.js"></script>

<script>

    $(document).ready(
        function () {
            MudarSelecaoPagina("Compras");
        }
    );
    function redirectToCompra(id) {
        window.location.href = "/compra/" + id;
    }

    function CadastrarCompraPre() {
        if (!ValidacaoCompra()) return;

        var url = "@Url.Action("CadastrarCompra", "Compra")";
            var params = {
                id: 0,
                data: $("#data").val(),
                descricao: $("#descricao").val(),
         };
            $("#Modal").modal("hide");

           $.post(url, params, CadastrarCompraPos);
    }

    function ExcluirCompraPre(id)
    {

        var url = "@Url.Action("ExcluirCompra", "Compra")/" + id;
            var params = {
                Id: id,
         };
            $("#Modal").modal("hide");
            $.post(url, params, ExcluirCompraPos);
    }
</script>