Pigeon.MVC/Controllers/RelatorioController.cs
using Pigeon.Dal.Repository;
using Pigeon.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pigeon.MVC.Controllers
{
    public class RelatorioController : Controller
    {
        // GET: Relatorio
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Genealogia(int idPombo, string anilha)
        {
            ArvoreGenealogica AG;
            PomboRepository Pr = new PomboRepository();

            if (idPombo != 0)
            {
                 AG = Pr.Genealogia(idPombo);
            }
            else
            {
                Pombo pombo = Pr.GetPomboByAnilha(anilha);
                if (pombo == null)
                    AG = null;
                else  AG = Pr.Genealogia(pombo.Id);
            }
                
             
            /*
             new ArvoreGenealogica()
            {
                mae = new Pombo() { Id = 0, Anilha = "XXX XXXX"  },
                pai = new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                avMat = new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                avoMat = new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                avPat = new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                avoPat = new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                pombo = new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                filhos = new List<Pombo>() {
                    new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                    new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                    new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                    new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                    new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                    new Pombo() { Id = 0, Anilha = "XXX XXXX" },
                },
                
            };*/

            if (AG == null)
            {
                return Json("Nenhum traço de genealogia encontrado");
            }
            return Json(AG);
        }

        [HttpGet]
        [Route("Relatorios")]
        public ActionResult Provas()
        {
            List<Prova> Provas; /*= new List<Prova>()
            {
                new Prova()
                {
                    id = 0,
                    descricao = "Prova do  Cabuloso"
                },
                new Prova()
                {
                    id = 0,
                    descricao = "Prova do  Cabuloso"
                },
                new Prova()
                {
                    id = 0,
                    descricao = "Prova do  Cabuloso"
                }
            }; */

            Provas = new ProvaRepository().GetAllProvas();
            return View(Provas);
        }

        [HttpPost]
        public ActionResult _BuscaPorPombo(int idPombo, string anilha, int idProva)
        {
            List<TuplaRelatorioProva> Tuplas =  new pombo_provaRepository().GetPombosEmProvas(idPombo, anilha, idProva);

            /*Tuplas = new List<TuplaRelatorioProva>() {
                new TuplaRelatorioProva()
                {
                    Id = 0,
                    Anilha = "AAA AAAA",
                    Prova = "Sapucaí do Brejo",
                    Colocacao = 2,
                    Velocidade = 74
                },
                 new TuplaRelatorioProva()
                {
                    Id = 0,
                    Anilha = "AAA AAAA",
                    Prova = "Sapucaí do Brejo",
                    Colocacao = 2,
                    Velocidade = 74
                },
                  new TuplaRelatorioProva()
                {
                    Id = 0,
                    Anilha = "AAA AAAA",
                    Prova = "Sapucaí do Brejo",
                    Colocacao = 2,
                    Velocidade = 74
                },
                   new TuplaRelatorioProva()
                {
                    Id = 0,
                    Anilha = "AAA AAAA",
                    Prova = "Sapucaí do Brejo",
                    Colocacao = 2,
                    Velocidade = 74
                }
            };*/

            return View(Tuplas);
        }


    }
}

Pigeon.MVC/Views/Relatorio/Genealogia.cshtml
@using Pigeon.Model
@model ArvoreGenealogica


<link href="~/Content/css/Pombo.css" rel="stylesheet">

<div class="row margem-top-45 shadow rounded" style="padding-bottom:40px;">
    <div class="col-md-12">
        <div class="row text-center">
            <div class="col-md-12">
                <h5 class="text-center"> Genealogia Pombo:  <span>@Model.pombo.Anilha</span></h5>
            </div>
        </div>

        <hr style="margin-top:0px;margin-bottom:0" />

        <div class="row margem-top-25">
            <div class="col-md-1"></div>
            <div class="col-md-9">
                <div class="row margem-top-25">
                    <span style="font-weight:bold">&emsp;&emsp;&emsp;&emsp;&nbsp;Pai:&emsp;</span>
                    <span class="badge badge-primary">@Model.pai.Anilha</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">&emsp;&emsp;&emsp;&ensp;Mãe:&emsp;</span>
                    <span class="badge badge-primary">@Model.mae.Anilha</span>
                </div>
                <div class="row margem-top-25">
                    <span style="font-weight:bold">Avô Paterno:&emsp;</span>
                    <span class="badge badge-primary">@Model.avPat.Anilha</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">Avó Paterna&emsp;</span>
                    <span class="badge badge-primary">@Model.avoPat.Anilha</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">Avô Materno:&emsp;</span>
                    <span class="badge badge-primary">@Model.avMat.Anilha</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">Avó Materna&emsp;</span>
                    <span class="badge badge-primary">@Model.avoMat.Anilha</span>
                </div>
                <div class="row margem-top-25">
                    <span style="font-weight:bold">&emsp;&emsp;&emsp;Filhos:&emsp;</span>
                    @foreach (var filho in Model.filhos)
                    {
                        <span class="badge badge-primary">@filho.Anilha</span> <span>&emsp;</span>
                    }
                    
                </div>
            </div>
        </div>

        @*<div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-9">
                    <div class="row">
                        <span style="font-weight:bold">Pombo:&emsp;</span>
                        <span class="badge badge-primary">XXX XXXXX</span>
                    </div>
                </div>
            </div>*@


    </div>
</div>

Pigeon.MVC/Views/Relatorio/Index.cshtml
<link href="~/Content/css/Pombo.css" rel="stylesheet">

<div class="row margem-top-45 shadow rounded" style="padding-bottom:40px;">


    <div class="col-md-12">
        <div class="row text-center">
            <div class="col-md-12">
                <h5 class="text-center"> Genealogia Pombo:  <span></span></h5>
            </div>      
        </div>
        
        <hr style="margin-top:0px;margin-bottom:0"/>

        <div class="row margem-top-25">
            <div class="col-md-1"></div>
            <div class="col-md-9">
                <div class="row margem-top-10">
                    <span style="font-weight:bold">&emsp;&emsp;&emsp;&emsp;&nbsp;Pai:&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">&emsp;&emsp;&emsp;&ensp;Mãe:&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                </div>
                <div class="row margem-top-10">
                    <span style="font-weight:bold">Avô Paterno:&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">Avó Paterna&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">Avô Materno:&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                    &emsp;&emsp;
                    <span style="font-weight:bold">Avó Materna&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                </div>
                <div class="row margem-top-10">
                    <span style="font-weight:bold">&emsp;&emsp;&emsp;Filhos:&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span> &emsp;
                    <span class="badge badge-primary">XXX XXXXX</span> &emsp;
                    <span class="badge badge-primary">XXX XXXXX</span> &emsp;
                    <span class="badge badge-primary">XXX XXXXX</span> &emsp;
                </div>
            </div>
        </div>

        @*<div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-9">
                <div class="row">
                    <span style="font-weight:bold">Pombo:&emsp;</span>
                    <span class="badge badge-primary">XXX XXXXX</span>
                </div>
            </div>
        </div>*@


    </div>
</div>

Pigeon.MVC/Views/Relatorio/Provas.cshtml
@using Pigeon.Model;
@model List<Prova>

<link href="~/Content/css/Pombo.css" rel="stylesheet">

@*<div class="row text-center  margem-top-45">
    <div class="col-md-12 text-center">
        <h5>Relatório de Provas</h5>
    </div>
    
</div>*@
<div class="row margem-top-45">
    <div class="col-md-12">
        <div class="accordion" id="accordionExample">

            <div class="card" >
                <div class="card-header" id="headingOne" style="background-color:white; cursor: pointer;">
                    
                        <div  data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <h6>
                                Relatório de Provas
                            </h6>                     
                        </div>
                </div>

                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="row">
                                <div class="col-md-3 form-group">
                                    <input type="number" class="form-control" id="tbxId" placeholder="Id">
                                </div>
                                <div class="col-md-3 form-group">
                                    <input type="text" class="form-control" id="tbxAnilha" placeholder="Anilha">
                                </div>
                            <div class="col-md-4 form-group">
                                <select id ="ddlProvas" class="form-control" onchange="OnselectProva()">
                                    <option selected value="0">Selecione Uma Prova</option>
                                    @foreach (var Pr in Model)
                                    {
                                        <option value="@Pr.id">@Pr.descricao</option>
                                    }
                                </select>
                            </div>
                                <div class="col-md-2 form-group">
                                    <button type="button" class="btn btn-primary" onclick="ConsultarProvaPorPomboPre()">Consultar</button>
                                </div>
                        </div>
                        <div class="row">

                            <div class="col-md-12">
                                <table id="tbPorPombo" class="table text-center table-hover d-none">
                                    <thead>
                                        <tr>
                                            <th scope="col">Id</th>
                                            <th scope="col">Anilha</th>
                                            <th scope="col">Prova</th>
                                            <th scope="col">Colocação</th>
                                            @*<th scope="col">Veloc. Med. Vôo</th>*@
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                </div>
            </div>


            <div class="card">
                <div class="card-header" id="headingTwo" style="background-color:white; cursor: pointer;">
                    <div data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <h6>
                            Ancestralidade
                        </h6>
                    </div>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">



                    <div class="card-body" @*style="padding-bottom:40px;"*@>
                        
                        <div class="row">
                            <div class="col-md-3 form-group">
                                <input type="number" class="form-control" id="tbxId2" placeholder="Id">
                            </div>
                            <div class="col-md-3 form-group">
                                <input type="text" class="form-control" id="tbxAnilha2" placeholder="Anilha">
                            </div>
                            <div class="col-md-2 form-group">
                                <button type="button" class="btn btn-primary" onclick="ConsultarAncestralidadePre()">Consultar</button>
                            </div>
                        </div>

                        <div class="row">
                            <div id="divAncestralidade" class="col-md-12 d-none">
                                <div class="row" style="padding-left:25px; padding-bottom:25px">
                                    

                                    <div class="col-md-12">
                                        <div class="row margem-top-25">
                                            <span style="font-weight:bold">&emsp;&emsp;&emsp;&emsp;&nbsp;Pai:&emsp;</span>
                                            <span id="spPai" class="badge badge-primary"></span>
                                            &emsp;&emsp;
                                            <span style="font-weight:bold">&emsp;&emsp;&emsp;&ensp;Mãe:&emsp;</span>
                                            <span id="spMae" class="badge badge-primary"></span>
                                        </div>
                                        <div class="row margem-top-25">
                                            <span style="font-weight:bold">Avô Paterno:&emsp;</span>
                                            <span id="spAvPat" class="badge badge-primary"></span>
                                            &emsp;&emsp;
                                            <span style="font-weight:bold">Avó Paterna:&emsp;</span>
                                            <span id="spAvoPat" class="badge badge-primary"> </span>
                                            &emsp;&emsp;
                                            <span style="font-weight:bold">Avô Materno:&emsp;</span>
                                            <span id="spAvMat" class="badge badge-primary"> </span>
                                            &emsp;&emsp;
                                            <span style="font-weight:bold">Avó Materna:&emsp;</span>
                                            <span id="spAvoMat" class="badge badge-primary"> </span>
                                        </div>
                                        <div id="divFilhos" class="row margem-top-25">

                                            @*<span class="badge badge-primary">@filho.Anilha</span> <span>&emsp;</span>*@
                                        </div>

                                    </div>



                                </div>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

<script>
    $(document).ready(
        function () {
            MudarSelecaoPagina("Relatorios");
        }
    );

    function ConsultarProvaPorPomboPre() {
        var url = "@Url.Action("_BuscaPorPombo", "Relatorio")";

        var params = {
            idPombo: $("#tbxId").val() == "" ? 0 : $("#tbxId").val(),
            Anilha: $('#tbxAnilha').val(),
            idProva: 0
        };

        ProgressBar();

        $.post(url, params, ConsultarProvaPorPomboPos);
    }

    function ConsultarProvaPorPomboPos(html) {

        StopProgressBar();
        $("#tbPorPombo tbody").html(html);
        $("#tbPorPombo").removeClass("d-none");
    };

    function OnselectProva()
    {
        var url = "@Url.Action("_BuscaPorPombo", "Relatorio")";

        var params = {
            idPombo: $("#tbxId").val() == "" ? 0 : $("#tbxId").val(),
            Anilha: $('#tbxAnilha').val(),
            idProva: $("#ddlProvas option:selected").val()
        };

        ProgressBar();

        $.post(url, params, ConsultarProvaPorPomboPos);
    }

    function ConsultarAncestralidadePre()
    {
        var url = "@Url.Action("Genealogia", "Relatorio")";

        var params = {
            idPombo: $("#tbxId2").val() == "" ? 0 : $("#tbxId2").val(),
            Anilha: $('#tbxAnilha2').val()
        };

        ProgressBar();

        $.post(url, params, ConsultarAncestralidadePos);
    }

    function ConsultarAncestralidadePos(genealogia) {
        var teste;
        try
        {
            teste = genealogia.indexOf("encontrado") != -1;
        }
        catch(a)
        {
            teste = false;
        }

        if (teste) {
            Mensagem("alerta", genealogia);
        }
        else {

            $("#spPai").text(genealogia.pai.Anilha);
            $("#spMae").text(genealogia.mae.Anilha);
            $("#spAvMat").text(genealogia.avMat.Anilha);
            $("#spAvoMat").text(genealogia.avoMat.Anilha);
            $("#spAvPat").text(genealogia.avPat.Anilha);
            $("#spAvoPat").text(genealogia.avoPat.Anilha);

            var filhos = "<span style='font-weight:bold'>&emsp;&emsp;&emsp;Filhos:&emsp;</span> ";

            $(genealogia.filhos).each(function (index, filho) {
                filhos = filhos.concat("<span class='badge badge-primary'>" + filho.Anilha + "</span> <span>&emsp;</span> ")
            });

            $("#divFilhos").html(filhos);

            $("#divAncestralidade").removeClass("d-none");
        }

        StopProgressBar();

    }
</script>

Pigeon.MVC/Views/Relatorio/_BuscaPorPombo.cshtml
@using Pigeon.Model;

@model List<TuplaRelatorioProva>

@{
    Layout = null;
}

@foreach (var T in Model)
{
    <tr>
        <th scope="row">@T.Id</th>
        <td>@T.Anilha</td>
        <td>@T.Prova</td>
        <td>@T.Colocacao</td>
        @*<td>@T.Velocidade</td>*@
    </tr>  

}