Pigeon.MVC/Controllers/PomboController.cs
using Pigeon.Dal.Repository;
using Pigeon.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pigeon.MVC.Controllers
{
    public class PomboController : Controller
    {

        // GET: Pombal
        public ActionResult Index()
        {
            return View(new PomboRepository().GetAllPombos());
        }

        [HttpGet]
        [Route("pombos/{id}", Name = "VisualizaPombo")]
        public ActionResult Pombos(int id)
        {
            DoencaRepository DR = new DoencaRepository();
            ViewBag.proximasProvas = new ProvaRepository().GetAllProvas();
            ViewBag.doencasCadastradas = DR.GetAllDoencas();
            ViewBag.provasDoPombo = buscarProvasPombo(id);
            ViewBag.DoencasDoPombo = (from D in new pombo_doencaRepository().GetpomboDoencaByPomboId(id)
                                      select DR.GetDoencaById(D.doencaID)).ToList();
            return View(new PomboRepository().GetPomboById(id));
        }

        [HttpPost]
        public ActionResult CadastrarPombo(Pombo pombo)
        {
            new PomboRepository().NovoPombo(pombo).ToString();
            return View("_NovoPombo", pombo);
        }


        [HttpPost]
        public ActionResult AlterarPombo(Pombo pombo)
        {
            string msg = new PomboRepository().AlterarPombo(pombo).ToString();
            return Json(msg);
        }

        [HttpPost]
        public ActionResult ExcluirPombo(int Id)
        {
            try
            {
                new PomboRepository().ExcluirPombo(Id);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(Id);
        }

        //pombo_prova
        [HttpPost]
        public ActionResult registrarPomboEmProva(int idPombo, int idProva) {
            int result = 0;
            try
            {
                pombo_prova meuPombo = new pombo_prova()
                {

                };
                meuPombo.pomboID = idPombo;
                meuPombo.provaID = idProva;
                new pombo_provaRepository().NovoPomboProva(meuPombo);
                result = 1;
            }
            catch (Exception e) {
                result = 0;
            }
            return Json(result);
        }

        public List<Prova> buscarProvasPombo(int idPombo) {
            List<Prova> resultado =  new List<Prova>();
            List<pombo_prova> provasDoPombo = new pombo_provaRepository().GetpomboProvaByPomboId(idPombo);
            foreach (pombo_prova prova in provasDoPombo)
            {
                resultado.Add(new ProvaRepository().GetProvaById(prova.provaID).First());
            }
            return resultado;
        }
        //pombo doenca
        [HttpPost]
        public ActionResult registrarDoencaEmPombo(int idPombo, int idDoenca)
        {
            int result = 0;
            try
            {
                pombo_doenca meuPombo = new pombo_doenca();
                meuPombo.pomboID = idPombo;
                meuPombo.doencaID = idDoenca;
                new pombo_doencaRepository().NovoPomboDoenca(meuPombo);
                result = 1;
            }
            catch (Exception e)
            {
                result = 0;
            }
            return Json(result);
        }

        public List<Doenca> buscarDoencasPombo(int idPombo)
        {
            List<Doenca> resultado = new List<Doenca>();
            List<pombo_doenca> DoencasDoPombo = new pombo_doencaRepository().GetpomboDoencaByPomboId(idPombo);
            foreach (pombo_doenca prova in DoencasDoPombo)
            {
                resultado.Add(new DoencaRepository().GetDoencaById(prova.doencaID));
            }
            return resultado;
        }
    }
}

Pigeon.MVC/Views/Pombo/Index.cshtml
@using Pigeon.Model
@model List<Pombo>

<link href="~/Content/css/Pombo.css" rel="stylesheet">


<div class="row margem-top-25">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"> <img src="~/Content/imgs/icons/search.png" height="25" /> </div>
            </div>
            <input type="text" class="form-control" id="tbxBuscar" placeholder="Buscar">
        </div>
    </div>
    <div class="col-md-1">
        <img class="clicavel" src="~/Content/imgs/icons/add_circle.png" height="36" onclick="ModalCadastroPombo();"/>
    </div>

</div>

<div class="row margem-top-10">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th scope="col">ID</th>
                    <th scope="col">Anilha</th>
                    <th scope="col">Sexo</th>
                    <th scope="col">Idade</th>
                    @*<th scope="col">Rank</th>*@
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Pombo P in Model)
                {
                    { Html.RenderPartial("_NovoPombo", P); }
                }
            </tbody>
        </table>

    </div>
</div>
<script src="~/Scripts/Pombo.js"></script>

<script>
    $(document).ready(
        function () {
            MudarSelecaoPagina("Pombos");
        }
    );

    function CadastrarPomboPre() {
        if (!ValidacaoPombo()) return;

        var url = "@Url.Action("CadastrarPombo", "Pombo")";
            var params = {
                Id: 0,
                Anilha: $("#tbxAnilha").val(),
                DataNasc: $("#tbxDataNasc").val(),
                Sexo: $("#ddlSexo option:selected").val()
         };
            $("#Modal").modal("hide");
            ProgressBar();
            $.post(url, params, CadastrarPomboPos);
    }

    function ExcluirPomboPre(id)
    {

         var url = "@Url.Action("ExcluirPombo", "Pombo")";
            var params = {
                Id: id,
         };
            $("#Modal").modal("hide");
            ProgressBar();
            $.post(url, params, ExcluirPomboPos);
    }

    function RedirecionarParaPombo(id) {

        window.location.href = '/Pombos/'+id;
    }

</script>

Pigeon.MVC/Views/Pombo/_NovoPombo.cshtml
@{
    Layout = null;
}

@using Pigeon.Model
@model Pombo

<tr id="Pombo-@Model.Id" class="text-center selecionar" onclick="RedirecionarParaPombo(@Model.Id);">
    
    <td>@Model.Id</td>
    <td>@Model.Anilha</td>
    <td>@Model.Sexo</td>
    <td>@(Convert.ToInt16(Math.Floor((DateTime.Now.Subtract(Model.DataNasc).Days) / 365.0)))</td>
    @*<td>@(Model.Rank.ToString() == "0" ? "--" : Model.Rank.ToString())</td>*@
    <td><img class="responsivo" src="~/Content/imgs/icons/remove.png" height="25" onclick="ModalExclusaoPombo(this);" /></td>
</tr>